# Generated by Django 4.1.2 on 2022-11-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='email',
            field=models.EmailField(default='nama@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='data',
            name='judul',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
