# Generated by Django 4.1.2 on 2022-11-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_data_email_alter_data_judul'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='alamat',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
